#! /usr/bin/env bash

img=${1:-map.jpeg}
out=${2:-flow.mp4}

set -e
s=$RANDOM
o=$(./storage.sh)
echo $o
jpegtopnm $img | pnmtopng > $o/img.png
set -x
flow/fluid -m10 -s $s -n 500 -i $o/img.png -o $o/_
flow/wave -m2 -s $s -i ${o}/_%u.jpeg -o $o/
./compiler.sh $o/ $out
