#! /usr/bin/env python3

from os import system
from sys import argv
from math import exp, log

# usage: give path of jpeg in a tree generated by genfei.py
#        produces a video sequence zooming into it
#        set the following four as was generated

tall = 2
side = 3

image_w = 960 * side
image_h = 540 * side

# note: i kept this because there are some interesting details
#       in the program.  however, i do not find the generated
#       video sequence at all beautiful

def s(c):
    print(c)
    system(c)

video_w = 1920
video_h = 1080

n_zoom = 64

def linear(a, b, t):
    return a + (b - a) * t

def delinear(a, b, t):
    return (t - a) / (b - a);

def reline(a, b, c, d, t):
    return linear(a, b, delinear(c, d, t))

def exintr(a, b, t):
    return exp(linear(log(a), log(b), t))

def zgen(to_x, to_y, j, paths, tmp):
    s("montage %s -geometry %dx%d+0+0 -tile %dx%d %s" % (
        " ".join(paths), image_w, image_h, side, side, tmp))
    for i in range(n_zoom):
        t = exintr(side, 1, i / n_zoom)
        w = image_w * t
        h = image_h * t
        x = reline(0, to_x, side, 1, t)
        y = reline(0, to_y, side, 1, t)
        s("convert %s -crop %dx%d+%d+%d -resize %dx%d %d.jpeg" % (
            tmp, w, h, x, y, video_w, video_h, i + j))

if len(argv) == 2:
    selected_path = argv[1]
    *base_dir, level_dir, y_dir, x_name = selected_path.split("/")
    base_dir = "/".join(base_dir)
    y_lev = int(level_dir)
    y_sel = int(y_dir)
    x_sel = int(x_name[:-5])

    levels = int(log(y_lev / (image_h * tall), side)) - 1

    i = n_zoom * levels
    while y_lev > image_h * tall:
        y_lev_up = y_lev // side
        y_sel_up = y_sel // side
        x_sel_up = x_sel // side
        rem_y = y_sel_up % image_h
        rem_x = x_sel_up % image_w
        y_sel_up -= rem_y
        x_sel_up -= rem_x
        to_y = rem_y * side
        to_x = rem_x * side
        y_grd = y_sel_up * side
        x_grd = x_sel_up * side

        tmp = "%s/%d/%s+%s.jpeg" % (base_dir, y_lev, x_sel, y_sel)
        paths = [("%s/%d/%06d/%06d.jpeg" % (
            base_dir, y_lev, y_grd + j * image_h, x_grd + i * image_w))
            for j in range(side) for i in range(side)]
        zgen(to_x, to_y, i, paths, tmp)
        i -= n_zoom

        y_lev = y_lev_up
        y_sel = y_sel_up
        x_sel = x_sel_up
