#! /usr/bin/env bash
#
# Usage:      upper lower height width pr
#
# coordinates are in femto count integers
# an image sequence generated by ./feigen

set -e

o=${1}
a=${2:-3750000000000000}
b=${3:-3753906250000000}
h=${4:-2160}
w=${5:-3840}
e=${6:-./feigen}
q=${7:-1}  # columns
u=1000000000000000
f(){
 printf %016d $((10#$1))
}
k=$((u / q))
seq $q |while read i
do
j=$((i - 1))
c=$((j * k))
d=$((i * k))
av="$(f $a) $(f $b) $(f $c) $(f $d)"
echo "$j: $av"

( echo -en "P5\n$w $h\n65535\n" &&
  $e $av $h $w ) | pnmtojpeg >"$o$j.jpeg"

done
