#! /usr/bin/env bash
#
# Usage:      upper lower height width pr
#
# coordinates are in femto count integers
# an image sequence generated by ./feigen

set -e

a=${2:-3000000000000000}
b=${3:-3003906250000000}
u=1000000000000000
h=${4:-2160}
w=${5:-3840}
e=${6:-./feigen}
q=${7:-256}
f(){
 printf %016d $((10#$1))
}
k=$((u / q))
seq "$q" |while read i
do
j=$((i - 1))
c=$((j * k))
d=$((i * k))
av="$(f $a) $(f $b) $(f $c) $(f $d)"
echo -n "$j: $av "
(   echo -en "P5\n$w $h\n65535\n" &&
       \time -f "%E" $e $av $h $w) |
    pnmtojpeg >"$j.jpeg"
done

